### PR TITLE
Fix specific typo

### PR DESCRIPTION
**Pull request by parndt**

### CODE REVIEW

**Comment by timriley** [comment]
You have my specific thanks, Phil

**Comment by parndt** [comment]
you are specifically welcome

**Comment by parndt** [comment]
@timriley do I have to do this for a docsite branch or something? How does it work?

**Comment by timriley** [comment]
Look, honestly, I can’t answer that right now. Need @solnic to write a summary of this stuff at some point 😬

**Comment by solnic** [comment]
@parndt @timriley I'm gonna announce and explain all of the recent changes/improvements in our docs/website infrastructure later this week. I'll be very specific. Stay tuned.

**Pull request merged**
